### PR TITLE
Reopening PR #23 to fix errored tests in adjoints.jl

### PR DESCRIPTION
**Pull request by arcAman07**
This PR resolves Issue https://github.com/SomTambe/DiffImages.jl/issues/22.
This PR has the sole motive to fix the 8 errored tests ( "@testset "ImageTransformations._getindex gradient" ) in the adjoints.jl file.
Type incompatibility was the issue for the tests failing which is resolved and now all of them are passing successfully.
Due to some compatibility issues with my text editor had to reopen a new PR. Hopefully the PR helps.

### CODE REVIEW

**Comment by johnnychen94** [comment]
Might need to open a format PR separately for the whitespace fix (e.g., https://github.com/JuliaImages/ImageMorphology.jl/pull/69)

**Review by johnnychen94 — APPROVED** [review]
Except for the whitespace fix, LGTM

**Comment by arcAman07** [comment]
> Might need to open a format PR separately for the whitespace fix (e.g., [JuliaImages/ImageMorphology.jl#69](https://github.com/JuliaImages/ImageMorphology.jl/pull/69))
> 
> I believe FluxML uses `indent=2`

Sure I will fix it, wasn't aware that it mess up the whitespaces. Should I open a new PR to fix these changes after it's merged or close this PR and open a new one ?

**Comment by johnnychen94** [comment]
> Should I open a new PR to fix these changes after it's merged or close this PR and open a new one ?

1. open a format-fix PR
2. merge that PR
3. rebase this PR branch on top of the new master. If there are any, resolve the conflicts. `git pull` or `git pull --rebase`

---

Usually, it's a good practice to develop on separate branches instead of on the `main` branch; because that way you can change between different PRs very easily.

**Comment by arcAman07** [comment]
The whitespaces are fixed 👍

**Pull request merged**
